# Generated by Django 5.2.14 on 2026-05-22 13:41

import django.utils.timezone
import users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RoomChat",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=users.utils.generate_nano_id,
                        editable=False,
                        max_length=16,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="RoomChatFile",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=users.utils.generate_nano_id,
                        editable=False,
                        max_length=16,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(upload_to="room_chat_files/%Y/%m/")),
                ("file_name", models.CharField(max_length=255)),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoomTypingStatus",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=users.utils.generate_nano_id,
                        editable=False,
                        max_length=16,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="TeamRoom",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=users.utils.generate_nano_id,
                        editable=False,
                        max_length=16,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
