# Generated by Django 5.2.14 on 2026-05-22 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tasks", "0002_initial"),
        ("team_rooms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="roomchat",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="room_chats",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="roomchatfile",
            name="uploaded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="roomchat",
            name="files",
            field=models.ManyToManyField(
                blank=True, related_name="chat_messages", to="team_rooms.roomchatfile"
            ),
        ),
        migrations.AddField(
            model_name="roomtypingstatus",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="teamroom",
            name="team",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="room",
                to="tasks.team",
            ),
        ),
        migrations.AddField(
            model_name="roomtypingstatus",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="typing_users",
                to="team_rooms.teamroom",
            ),
        ),
        migrations.AddField(
            model_name="roomchat",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chats",
                to="team_rooms.teamroom",
            ),
        ),
        migrations.AddIndex(
            model_name="roomtypingstatus",
            index=models.Index(
                fields=["room", "expires_at"], name="team_rooms__room_id_477ced_idx"
            ),
        ),
    ]
