# Generated by Django 5.2.14 on 2026-05-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_alter_task_options_remove_task_completed_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaltask",
            name="estimated_hours",
        ),
        migrations.RemoveField(
            model_name="task",
            name="estimated_hours",
        ),
        migrations.AddField(
            model_name="historicaltask",
            name="estimated_duration",
            field=models.DurationField(
                blank=True,
                help_text="Estimated duration (e.g., '1 02:00:00' for 1 day, 2 hours)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="estimated_duration",
            field=models.DurationField(
                blank=True,
                help_text="Estimated duration (e.g., '1 02:00:00' for 1 day, 2 hours)",
                null=True,
            ),
        ),
    ]
